# permissions for end users to edit harborprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: harborproject-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: harbor-operator
    app.kubernetes.io/part-of: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: harborproject-editor-role
rules:
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborprojects/status
  verbs:
  - get
