# permissions for end users to view projects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: project-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: harbor-operator
    app.kubernetes.io/part-of: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-viewer-role
rules:
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - projects/status
  verbs:
  - get
