---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborprojects/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborservices/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.mdlwr.com
  resources:
  - harborservices/status
  verbs:
  - get
  - patch
  - update
