name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Go Vet
      run: make vet
    - name: Go Test
      run: make test
      
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Compile
      run: make